services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  rabbitmq-reciver:
    image: rabbitmq-reciver:lastest
    depends_on:
      - rabbitmq
    ports:
      #  local : container expose
      - "8081:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
  rabbitmq-sender:
    image: rabbitmq-sender:lastest
    depends_on:
      - rabbitmq
    ports:
      #  local : container expose
      - "8082:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
